# Header
menu:
  ## If your site is put in a subdirectory, set Home as '/child/'
  Home: /
  Archives: archives

social:
  email: ooiss@qq.com
  twitter:
  github: iamcco
  googleplus:
  rss: /atom.xml

# Content
fancybox: true # set to true if you want to use it

duoshuo: yuukocn
disqus: #disqus _shortname
